#!/bin/bash

INSTANCE=$(screen -li | grep elastic | sed 's/\s/ /g')

if [ -n "$INSTANCE" ]
then
    echo "Already running: $INSTANCE"
else
    mkdir -p /vagrant/logs

    screen -S elastic -d -m bash -l -c "elasticsearch -Des.config=/vagrant/conf/elasticsearch-$VM_NAME.yml > /vagrant/logs/elasticsearch-$VM_NAME.log 2>&1"
    echo "-----------------------------------------------------------------------------------------------------------"
    echo " => Started $VM_NAME - $VM_NODE_NAME - $VM_NODE_IP: $(screen -li | grep elastic | sed 's/\s/ /g')"
    echo "-----------------------------------------------------------------------------------------------------------"
fi
