#!/bin/bash

INSTANCE=$(screen -li | grep elastic | sed 's/\s/ /g')

if [ -n "$INSTANCE" ]
then
    echo "Already running: $INSTANCE"
else
    screen -S elastic -d -m bash -l -c "elasticsearch -Des.config=/vagrant/conf/$VM_NAME/elasticsearch.yml"
    echo "Started $VM_NAME: $(screen -li | grep elastic | sed 's/\s/ /g')"
fi
